# Generated by Django 3.2.2 on 2021-05-14 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('swiggy_auth_token', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('zomato_auth_token', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Detail',
            },
        ),
    ]
