# Generated by Django 3.2.2 on 2021-05-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='cultfit_auth_token',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
