# Generated by Django 3.2.2 on 2021-05-16 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_details', '0002_userdetail_cultfit_auth_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('city', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('date', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('bill_type', models.CharField(choices=[('food_bill', 'Food Bill'), ('learning_budget_bill', 'Learning Budget Bill'), ('internet_bill', 'Internet Bill')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Bill Detail',
            },
        ),
    ]
