# Generated by Django 3.2.2 on 2021-05-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0003_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
