# Generated by Django 3.2.2 on 2021-05-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0004_bill_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='storage_link',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
